title: Texas-C's Blog
description: "A Jekyll based Blog"
author:
  name: "Forrest"
  email: "ytexas@yahoo.com"
  url: "https://texas-c.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Forrest"
year : "2019"
